pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Model_CI'
  displayName: 'Data Ingestion'
  jobs:
  - job: "Model_CI_Pipeline"
    displayName: "Data Ingestion"
    timeoutInMinutes: 0
    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          # Invoke the Python building and publishing a training pipeline
          python -m ml_service.pipelines.data_ingestion_pipeline
      displayName: 'Data Ingestion Pipeline'
