# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, registration, deployment, and testing of the diabetes_regression model.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - kaggle_titanic/

variables:
- template: runtime-variables-template.yml
- group: Azure-SCN

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Model_CI'
  displayName: 'Model CI'
  condition: not(variables['MODEL_BUILD_ID'])
  jobs:
  - job: "Model_CI_Pipeline"
    displayName: "Model CI Pipeline"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - task: Bash@3
      displayName: 'Install dependencies'
      inputs:
      targetType: filePath
      filePath: './environment_setup/install_requirements.sh'
    - template: code-quality-template.yml
    - task: AzureCLI@1
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          # Invoke the Python building and publishing a training pipeline
#          python -m ml_service.pipelines.diabetes_regression_build_train_pipeline
          echo "Print reached"
      displayName: 'Publish Azure Machine Learning Pipeline'
